<html><header><title>Bug? Csla.Rules.BusinessRules.RunRules() hides Exceptions in rules</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Bug? Csla.Rules.BusinessRules.RunRules() hides Exceptions in rules</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/11787.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>Holger posted on Tuesday, January 15, 2013</h2><p><span style="font-family:Consolas;font-size:x-small;"><span style="font-family:Consolas;font-size:x-small;"><span style="font-family:Consolas;color:#0000ff;font-size:x-small;"><span style="font-family:Consolas;color:#0000ff;font-size:x-small;"><span style="font-family:Consolas;color:#0000ff;font-size:x-small;">
<p>We&nbsp;log all unhandeled&nbsp;exceptions for monitoring. I have a case where an exception occurs in the business rule execute-method. We can not monitor those exception, because the BusinessRules-class does not rethrow.</p>
<p>There is a try-catch block in Csla.Rules.BusinessRules.RunRules() method which hides exceptions on rule execution.&nbsp;</p>
<p>Is it possible to fix this&nbsp;and rethrow&nbsp;this exception?</p>
<p>try<br />{<br />&nbsp;&nbsp; rule.Execute(context);<br />}<br />catch (Exception ex)<br />{<br />&nbsp;&nbsp; context.AddErrorResult(string.Format(&quot;{0}:{1}&quot;, rule.RuleName, ex.Message));<br />&nbsp;&nbsp;&nbsp;if (rule.IsAsync)<br />&nbsp;&nbsp;&nbsp;&nbsp; context.Complete();</p>
<font face="Consolas" size="2" color="#0000ff"><font face="Consolas" size="2" color="#0000ff"><font face="Consolas" size="2" color="#0000ff">
<p><strong>&nbsp;&nbsp; throw;</strong><br />}</p>
</font></font></font></span><font face="Consolas" size="2" color="#0000ff"><font face="Consolas" size="2" color="#0000ff">
<p>&nbsp;</p>
</font></font></span><font face="Consolas" size="2" color="#0000ff">
<p>&nbsp;</p>
</font></span>
<p><span style="font-family:Consolas;font-size:x-small;"><span style="font-family:Consolas;font-size:x-small;"></span></span></p>
</span></span></p></div><div style='padding:0 15 3 15;background-color:lightgreen'><h2>JonnyBee replied on Thursday, January 17, 2013</h2><p>An unhandled exception in a rules Execute method will be added as a broken rule to that property/object.&nbsp;</p>
<p>We cannot allow unhandled exception in rules to be thrown as you suggest as this would stop the entire rule processing and leave the object in an indetermined state.&nbsp;</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>Holger replied on Thursday, January 17, 2013</h2><p>Is it possible to add a setting in app.config, so that the user of the csla-framwork&nbsp;can decide to rethrow exceptions in rules or not?</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>JonnyBee replied on Thursday, January 17, 2013</h2><p>No, the only solution will require extending the rules framework to accept a custom exception logger - which is not supported at the time. </p>
<p>CSLA can not rethrow the exception - the rule subsystem MUST make sure to check all rules and not leave the object in an undetermined state and you may get more than one exception. Remenber also to handle a combination of sync and async rules.</p>
<p>Your only option - right now - is to edit the CSLA source locally to create your own CSLA version and add exception logging in BusinessRules.RunRules</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>Holger replied on Wednesday, January 23, 2013</h2><p>Ok, I think about to create my own CSLA version.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
