<html><header><title>ObjectDisposedException</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>ObjectDisposedException</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/11839.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>rfcdejong posted on Friday, February 15, 2013</h2><p>This could just be in debug with exception&#39;s on, but i wonder if this might be a bug..</p>
<p>At ApplicationContext the GetLocalContext() method throws: &quot;Cannot access a closed file&quot;</p>
<p>&nbsp;</p>
<p>It happens when the GC finalize an ObjectFactory which dispose the repository using a Csla.Data.EF5.DbContextManager which does a DeRef as being a IDisposable. It wants to remove the ContextLabel from the ApplicationContext.LocalContext.</p>
<p>Somehow the LocalDataStoreSlot is closed before the DbContextManager is being finalized.</p>
<p><br />PS: The backend - server side code - is hosted in IIS with Apppool recycling on. I think it happens when the Apppool is recycled.</p>
<p>It could be that i have to force a dispose the ContextManager after using it? But that might be a problem since the factory&#39;s are somehow a unit of work and while the unit of work is running the ContextManager must be up. There is no memory leak, the GC is just not disposing fast enough. The LocalDataStoreSlot is just gone.</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>rfcdejong replied on Tuesday, March 12, 2013</h2><p>This is becomming a problem, the DbContextManager is being finalized after the NamedDataslot has been freed.</p>
<p>The InvalidOperationException with message &quot;LocalDataStoreSlot storage has been freed&quot; is being thrown whenever the GC comes by to dispose the DbContextManager.</p>
<p>Since we are not using code that forces to dispose after usage, can it be made a bit safer? Maybe a check if the context hasn&#39;t been disposed before accessing it?</p>
<p>Our code:<br />The root factory creates have a IRepository injected.<br />The classes implementing IRepository create a DbContextManager in the constructor and implementing IDisposable they dispose the DbContextManager when all the factory&#39;s holding a reference to the repository are disposed.</p>
<p>In the DeRef the RefCount get to 0 and then it want to execute the following code resulting into the exception.</p>
<p>&nbsp;</p>
<p>
<p>&nbsp; &nbsp; private void DeRef()<br /><span style="font-size:12px;">&nbsp; &nbsp; {<br />&nbsp;</span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; lock (_lock)<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp;{<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; _refCount -= 1;<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; if (_refCount == 0)<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; {<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _context.Dispose();<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ApplicationContext.LocalContext.Remove(ContextLabel);<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; &nbsp; }<br /></span><span style="font-size:12px;">&nbsp; &nbsp; &nbsp; }<br /></span><span style="font-size:12px;">&nbsp; &nbsp; }</span></p>
</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Tuesday, March 12, 2013</h2><p>LocalContext is stored in thread local storage. So you are saying that the thread is gone before all the using blocks have been exited?</p>
<p>I guess I&#39;m not understanding the scenario you are describing...</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>rfcdejong replied on Wednesday, March 13, 2013</h2><p>We aren&#39;t using &#39;using blocks&#39;. The thread and later on the GC comes by, something like that.</p>
<p>The exception takes a time to happen, the thread is not directly gone, we also don&#39;t force the GC to collect.</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Wednesday, March 13, 2013</h2><p>The data object context objects in Csla.Data are _designed_ for using blocks. The entire point of these types is to do reference counting so the underlying objects are disposed appropriately.</p>
<p>If you aren&#39;t either using a using block or manually calling dispose on the context object I would _expect_ there to be problems. That&#39;s not a bug, that&#39;s the way these types are designed to function.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
