<html><header><title>DataPortal.CreateAsync does not call DataPortal_Create through the data portal using CSLA 4.5.501</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>DataPortal.CreateAsync does not call DataPortal_Create through the data portal using CSLA 4.5.501</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/12581.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>Russ posted on Thursday, April 10, 2014</h2><p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">I am creating a Silverlight 5 application with the latest CSLA 4.5.501 (installed via Nuget). I am using the new async await syntax and have discovered that DataPortal.CreateAsync does not call the DataPortal_Create method on a simple BusinessBase object.</span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">If I change the DataPortal.CreateAsync call to DataPortal_FetchAsync in the factory method then it successfully calls the DataPortal_Fetch method through the data portal. </span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">Calling the CreateAsync with no parameters does not call the &ldquo;protected override void DataPortal_Create()&rdquo; method and calling CreateAsync with a single string parameter does not call the &ldquo;protected void DataPortal_Create(string username)&rdquo;.</span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">If I flag the DataPortal_Create method as [RunLocal] and move it outside the #if !SILVERLIGHT #endif block then the CreateAsync call works.</span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">Adding a try catch around the DataPortal.CreateAsync call does not catch any exceptions.</span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;"><span style="font-family:Calibri;">I know my WCF configuration is correct because the DataPortal_Fetch works.</span></span></p>
<p style="margin:0in 0in 8pt;" class="MsoNormal"><span style="font-size:small;font-family:Calibri;">Has anyone else observed this behaviour?</span></p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Tuesday, April 22, 2014</h2><p>The failure case is with a remote data portal?</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>Russ replied on Tuesday, April 22, 2014</h2><p>Yes.&nbsp; My WCF configuration is copied from&nbsp;CSLA4.5.500\Samples\Net\cs\SimpleNTier solution.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
