<html><header><title>Exceptions not being raised</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Exceptions not being raised</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/4311.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 posted on Thursday, February 07, 2008</h2>Hi,<br><br>I recently overrode DataPortal_OnDataPortalException in my Csla derived base classes.&nbsp; The idea was that if an error happens on the dataportal and remoting was being used, the exception details could be emailed to me.&nbsp; Failing that, an attempt is made to write to the Event log.<br><br>Since I've added this, exceptions on the data portal no longer seem to be raised back to the client.&nbsp; In fact, the transaction completes successfully even though not all of the data was written.&nbsp; (using transaction scope).<br><br>Now, I believe that my attempt to write to the event log is causing an exception which I'm not catching.. but I'm disturbed by the fact that it seems the exception is being lost somewhere.<br><br>Has anyone else come across this?<br><br>Thanks<br>Andy<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>david.wendelken replied on Thursday, February 07, 2008</h2>Maybe your new code has a boo-boo in it.&nbsp; Care to post it so we can take a look too?</div><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 replied on Friday, February 08, 2008</h2>Sorry, I was out most of yesterday.<br><br>Here's the override code.<br><br>Find attached the ExceptionEmailer class.<br><br>Thanks<br>Andy<br><br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /// &lt;summary&gt;In a remoting scenario, the error email from the client<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /// isn't useful anymore, so send the email here, but still allow it<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /// to bubble up to the client.&lt;/summary&gt;<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /// &lt;param name="e"&gt;Data portal event arguments.&lt;/param&gt;<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /// &lt;param name="ex"&gt;The exception which occured.&lt;/param&gt;<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; protected override void DataPortal_OnDataPortalException( <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; DataPortalEventArgs e, <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; Exception ex <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ) {<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; if ( ApplicationContext.ExecutionLocation == <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ApplicationContext.ExecutionLocations.Server ) {<br><br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ExceptionEmailer.SendErrorEmail( ex );<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }<br><br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; base.DataPortal_OnDataPortalException( e, ex );<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 replied on Friday, February 08, 2008</h2>After posting this code, I reviewed it and realized it would not be thread safe, which is bad because I'm using remoting and IIS.. so that static Exception variable could be changed by many threads.<br><br>I now use ParameterizedThreadStart and removed and static fields from that class.&nbsp; Maybe this was causing an issue?&nbsp; I don't know.. I still need to test to ensure exceptions are not getting lost.<br><br>Andy<br></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
