<html><header><title>CslaDataProvider swallows errors?  Or something else?</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>CslaDataProvider swallows errors?  Or something else?</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/4776.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 posted on Wednesday, April 30, 2008</h2>Hi,<br><br>I'm just getting started with the CslaDataProvider.&nbsp; Here's my Xaml:<br><br>&nbsp;&nbsp;&nbsp; &lt;Window.Resources&gt;<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &lt;Csla:CslaDataProvider <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; x:Key="ApplicationList"<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ObjectType="{x:Type Deployment:ApplicationList}"<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ManageObjectLifetime="False"<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; FactoryMethod="GetApplications"<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; IsAsynchronous="False"<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; /&gt;<br>&nbsp;&nbsp;&nbsp; &lt;/Window.Resources&gt;<br><br>The problem is that while the Factory method is properly being called, if there's any exception thrown in the process, nothing seems to happen.&nbsp; My window opens and displays, but empty.&nbsp; Shouldn't an exception be coming through somewhere?&nbsp; What's going on?<br><br>Thanks<br>andy<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>Paul Czywczynski replied on Wednesday, April 30, 2008</h2>WPF will not not throw up an exception dialog when there are binding errors. The output window is your friend when designing WPF forms. VS will show the binding exceptions/errors in the output window. Most of my team keeps the window open on an other monitor during debugging sessions. If that doesn't work for you, try Josh Smith's Mole plugin for VS and/or create a simple pass-thru converter to use in your binding expression and set a breakpoint in the converter to look at your live data in VS's locals window.<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 replied on Thursday, May 01, 2008</h2>Ugh.&nbsp; That's a problem.&nbsp; If my factory method throws an exception, I need to display an access denied message to the user.&nbsp; Also, for any other unhandled exceptions, in my WinForms application I have my own error dialog and handling (which emails me exception details).&nbsp; <br><br>Since most of the errors happen during data access, that's going to make informing the user much more difficult.<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>Paul Czywczynski replied on Thursday, May 01, 2008</h2>Here is some code on how we handle it. We resorted to manually coding all our databinding. It uses a lot of our own functions but you see the paradigm we use:<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; protected override void DataBindForm()<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; using (_odp.DeferRefresh())<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _odp.ObjectType = typeof(EmployeeDetails);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _odp.FactoryMethod = "GetEmployeeDetails";<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _odp.IsAsynchronous = true;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _odp.DataChanged += new EventHandler(Odp_DataChanged);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _odp.FactoryParameters.Add(this.CurrentPageJournalItem.PrimaryKey.OriginId);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; private void Odp_DataChanged(object sender, EventArgs e)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if (_odp.Error != null)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Helpers.ExceptionHandler(_odp.Error);<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if (_odp.Data != null &amp;&amp; this.DataContext == null)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this.DataContext = _odp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (_odp.Data as EmployeeDetails).PropertyChanged += new PropertyChangedEventHandler(Details_PropertyChanged);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; private void Form_Unloaded(object sender, RoutedEventArgs e)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this.SaveCompleted -= Form_SaveCompleted;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (this._odp.Data as EmployeeDetails).PropertyChanged -= Details_PropertyChanged;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this._odp.DataChanged -= Odp_DataChanged;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this._odp = null;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br><br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 replied on Thursday, May 01, 2008</h2>So the solution is to hook into the DataChanged event and check errors there.. seems easy enough, although it should be unnessary.<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Friday, May 02, 2008</h2><P>That is the solution - and it makes sense if you think about all the options.</P>
<P>The CslaDataProvider (or any data provider for that matter) is not invoked by your code. So you can't wrap it in a try..catch block. So there must be some eventing scheme by which it notifies you of any issues. They chose to consolidate all notifications into the single DataChanged event rather than having various events for success/fail/etc.</P>
<P>Then consider that some data providers (including CslaDataProvider) support asynchronous loading of data (IsAsynchronous="True") - a feature that seriously rocks!! But in that case things are even more fun because not only is the data provider not invoked by your code, but it runs on a background thread. So dealing with issues could be even <EM>more</EM> complex, but they aren't, because the same eventing model services this scenario as well.</P></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
