<html><header><title>[Csla 3.5] Implications with the DataPortal doing AuthorizationRules.CanXYZObject checks</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>[Csla 3.5] Implications with the DataPortal doing AuthorizationRules.CanXYZObject checks</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/5421.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>stefan posted on Thursday, September 18, 2008</h2>Hi Rocky,<br><br>I noticed that the DataPortal, as a result of a negative AuthorizationRules check, does this <br>(in the case of Fetch):<br><font size="2">&nbsp;&nbsp;&nbsp; &nbsp; ...<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OnDataPortalInitInvoke(null);<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if (!Csla.Security.AuthorizationRules.CanGetObject(objectType))<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new System.Security.SecurityException(string.Format(Resources.UserNotAuthorizedException,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "get",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objectType.Name));<br>&nbsp;&nbsp;&nbsp; &nbsp; ...<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (Exception ex)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OnDataPortalInvokeComplete(new DataPortalEventArgs(dpContext, objectType, DataPortalOperations.Fetch, ex));<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ...<br></font>Normally I would expect some custom exception, maybe wrapping the SecurityException, <br>that lets us react accordingly. Telling the user about a missing authorization should happen <br>in a readable manner. Building the message using a string literal "get" and the typename only <br>works in English. You should at least provide some enum value here instead.<br><br>Another question: How do I subscribe to OnDataPortalInvokeComplete in my business object.<br>I have an override of DataPortal_OnDataPortalInvokeComplete, but it does not get called when <br>the above exception is raised...<br>
<br><br>Stefan<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Thursday, September 18, 2008</h2><P>Thanks for the feedback Stefan,</P>
<P>I think that if this exception gets thrown, it is because the UI developer didn't do their job. The UI should have use CanGetObject() to prevent the user from even trying to do the wrong thing, so the fact that the user was allowed to get here is a bug in the UI code.</P>
<P>But you are right - the literal string should be a resource. I'll add this to the to-do list.</P>
<P>Regarding the data portal - there are several virtual methods available. InvokeComplete is only called if the operation succceeds. There's another one (InvokeException maybe?) that is called when an exception occurs.</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>stefan replied on Thursday, September 18, 2008</h2>But looking at the snippet I posted, it looks like InvokeComplete <i>is</i> called in the case of an error occuring, with the EventArgs containing the exception...<br><br>Stefan<br><br><br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Thursday, September 18, 2008</h2>






 

 
  
 




<div class=Section1>

<p class=MsoNormal><span>Oh, I&#8217;m sorry, I got it confused with the virtual methods&#8230;<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>You are right, these are static events on the DataPortal class itself.<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>To handle that event, you need to set up an event handler. You must
be careful where you do this, because hooking an event causes a reference from
the event source (DataPortal) to the handler. Since this is a static event,
that reference will never go away unless you unhook the event &#8211; which can
lead to memory leaks.<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>But to hook the event, you just use standard event handling
code. += in C# and AddHandler in VB.<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>Csla.DataPortal.InvokeComplete += MyHandler;<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>AddHandler Csla.DataPortal.InvokeComplete, AddressOf MyHandler<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span>Rocky<o:p></o:p></span></p>

<p class=MsoNormal><span><o:p>&nbsp;</o:p></span></p>

<div>

<p class=MsoNormal><b><span>From:</span></b><span> stefan
[mailto:cslanet@lhotka.net] <br>
<b>Sent:</b> Thursday, September 18, 2008 9:08 AM<br>
<b>To:</b> rocky@lhotka.net<br>
<b>Subject:</b> Re: [CSLA .NET] [Csla 3.5] Implications with the DataPortal
doing AuthorizationRules.CanXYZObject checks<o:p></o:p></span></p>

</div>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>But looking at the snippet I posted, it looks like
InvokeComplete <i>is</i> called in the case of an error occuring, with the
EventArgs containing the exception...<br>
<br>
Stefan<br>
<br>
<br>
<br>
<br>
<o:p></o:p></p>

</div>



</div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
