<html><header><title>Throwing the concurrent access message down to the Silverlight client</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Throwing the concurrent access message down to the Silverlight client</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/9091.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>chrisdot posted on Wednesday, June 16, 2010</h2><p>Hello,</p>
<p>I&#39;m using the latest 3.8 of cslalight on both client and server side (SL4).</p>
<p>I would like to manage the concurrent DB access problem. I decided to use the timestamp technique to handle that like explained in <a href="http://forums.lhotka.net/forums/p/7015/33580.aspx">this thread</a>. But this is not really the problem here.</p>
<p>My question is rather about finding a way to propagate this information down to the client. Suppose we are updating a business object. Once we have reached the DataPortal_Update() on the server side, and that we have detected the concurrent access problem, what would be the&nbsp;relevant strategy to&nbsp;notify the silverlight client ?&nbsp;</p>
<p>Naturally, I was thinking&nbsp;of using the exceptions to handle that. But as I could read <a href="http://forums.lhotka.net/forums/p/6804/32632.aspx">here</a>, <a href="http://forums.lhotka.net/forums/p/8171/39036.aspx">here</a>, and <a href="http://forums.lhotka.net/forums/p/7127/34112.aspx">here</a>, as SL is not the same framework as full .NET, we can&#39;t serialize the exceptions on server and just deserialize them on the client, and that&#39;s why evrything is &quot;pasted&quot; into DataPortalException.(ErrorInfo of DataPortalException on client side).</p>
<p>But, I consider the case of the concurrent access problem is not the same as another general error (let&#39;s say a fatal error, where we could not do anything). I just would like to notify user that he should reload the date or something like that. How can I make a distinction&nbsp;of the exception coming&nbsp;to the client side? I started overriding the DataPortalException class, but it&nbsp;doesn&#39;t&nbsp;seem to be the relevant way. (Basically, I don&#39;t want to have to extract strings in the DataPortalException.Message, because I hate handling strings, and additionnaly, the [collapse]original message of the exception is a subset of the transported exception message. CSLA is doing some string.format() around it before sending it through the wires)&nbsp;</p>
<p>Does anyone have an idea to solve that, or another strategy? (even other than using exceptions) I browsed through the samples, but could not find anything about that (in the book neither)...</p>
<p>Thank you,</p>
<p>Christophe</p>[/collapse]</div><div style='padding:0 15 3 15;background-color:lightgreen'><h2>rnb replied on Wednesday, June 16, 2010</h2><p>Hi Christophe,</p>
<p>You&#39;re on the right track with the ErrorInfo.&nbsp; The structure is similar to the way inner exceptions are nested.&nbsp; So if your custom concurrent exception is the lowest level, you&#39;ll want to drill down the ErrorInfo.InnerError all the way down to the last one.&nbsp; You can then compare the ExceptionTypeName to your exception class name.&nbsp; You can also link and compile your existing exception class file into your Silverlight library project so you can compare it to the FullName property.&nbsp; So, something like:</p>
<p>if (errorInfo.ExceptionTypeName == typeof(ConcurrentException).FullName)</p>
<p>...</p>
<p>&nbsp;</p>
<p>That&#39;s the closest to a strongly typed solution that I can think of.</p>
<p>Good luck.</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>chrisdot replied on Thursday, June 17, 2010</h2><p><span lang="EN-US">Thank you MB for your answer. </span></p>
<p><span lang="EN-US">I tried to rely on your idea, but I could not achieve anything significant.</span></p>
<p><span lang="EN-US">Here is what I&#39;ve done. First I created my </span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;color:blue;">public</span><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;"> <span style="color:blue;">class</span> <span style="color:#2b91af;">ConcurrencyException</span> : <span style="color:#2B91AF;">DataPortalException</span></span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">{</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:blue;">public</span> ConcurrencyException(<span style="color:blue;">string</span> message, <span style="color:blue;">object</span> businessObject)</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-size:9.5pt;font-family:Consolas;">:<span style="color:blue;">base</span>(message, businessObject)</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;">}</span></p>
<p class="MsoNormal"><span>&nbsp;</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;line-height:115%;">Then, when in the DataPortal update method (handling my concurrency tests), I put the following (just throwing my new exception) :</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;color:blue;">protected</span><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;"> <span style="color:blue;">override</span> <span style="color:blue;">void</span> DataPortal_Update()</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">{</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:green;">//...</span></span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:blue;">throw</span> <span style="color:blue;">new</span> <span style="color:#2B91AF;">ConcurrencyException</span>(<span style="color:#A31515;">&quot;Concurrent access&quot;</span>, <span style="color:blue;">this</span>);</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-size:9.5pt;font-family:Consolas;color:green;">//...</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span style="font-size:9.5pt;font-family:Consolas;">}</span></p>
<p class="MsoNormal"><span lang="EN-US">&nbsp;</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;line-height:115%;">Finally, on my SL client side, I test my error info :</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;color:blue;">private</span><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;"> <span style="color:blue;">void</span> SaveDone(<span style="color:blue;">object</span> source, <span style="color:#2B91AF;">DataPortalResult</span>&lt;<span style="color:#2b91af;">CVisitDetailBO</span>&gt; args)</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">{</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:blue;">if</span> (args.Error != <span style="color:blue;">null</span>)</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:#2B91AF;">DataPortalException</span> custom_excp = args.Error <span style="color:blue;">as</span> <span style="color:#2b91af;">DataPortalException</span>;</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:blue;">string</span> exception_name = custom_excp.ErrorInfo.ExceptionTypeName;</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:green;">//!!!!</span></span></p>
<p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:35.4pt;margin-bottom:.0001pt;text-indent:35.4pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;color:green;">//And here, exception_name is still &quot;DataPortalException&quot; Is that correct ?</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></p>
<p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:normal;text-autospace:none;"><span lang="EN-US" style="font-size:9.5pt;font-family:Consolas;">}</span></p>
<p class="MsoNormal"><span lang="EN-US">&nbsp;</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;line-height:115%;">What did I miss? What should I do?</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;line-height:115%;">Thanks, Christophe</span></p></div><div style='padding:0 15 3 15;background-color:lightgreen'><h2>rnb replied on Thursday, June 17, 2010</h2><p>All exceptions gets wrapped inside a DataPortalException.&nbsp; So what you want to do is get the innermost error.</p>
<p><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; private static WcfErrorInfo GetInnermostErrorInfo(DataPortalException exception)<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; WcfErrorInfo errorInfo = exception.ErrorInfo;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; while (errorInfo.InnerError != null)<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; errorInfo = errorInfo.InnerError;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return errorInfo;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</p>
<p>&nbsp;</p>
<p>That should give you &quot;Namespace.ConcurrencyException&quot;</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>chrisdot replied on Friday, June 18, 2010</h2><p>Hello RNB,</p>
<p>Ok, now I understand (sorry, I should have found that alone). This is exactly what I need !</p>
<p>Thanks a lot!!</p>
<p>Christophe</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>skagen00 replied on Friday, June 18, 2010</h2><p>I actually have a ConcurrencyException myself and I dig into the exception if it&#39;s a dataportalexception to check for concurrency exception... it works just fine - just set a debug breakpoint and open up the exception until you find exactly where the concurrency exception can be detected (I don&#39;t have code in front of me right now).</p>
<p>&nbsp;</p>
<p>&nbsp;</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>chrisdot replied on Friday, June 18, 2010</h2><p>@skagen00: just in case, if you find&nbsp;the example, I would still be interested&nbsp;just to&nbsp;gather different ideas.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
